### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jalew188**
Release of 1.3.0

### CODE REVIEW

**Comment by jalew188** [comment]
> Hi, what do you think about raising the version to 2.0 with the new modifications?

We have discussed about this before. Before alphabase's paper publish, we can still use 1.x.x for breaking changes. This can prevent version 2000.x.x due to too many breaking changes as we still modify alphabase time to time.

**Comment by jalew188** [comment]
As long as the paper is published (BioRxiv), we will release the version 2.0.0 and then we will follow the right version control criteria.

**Comment by GeorgWa** [comment]
Okay 👍

**Review by GeorgWa — APPROVED** [review]
Lgtm

**Pull request merged**
