### PR TITLE
auto-fix more linting issues

### PR DESCRIPTION
**Pull request by mschwoer**
I added and fixed more linting rules.

### CODE REVIEW

**Comment by jalew188** [comment]
LGTM.

**Review by jalew188 — APPROVED** [review]

**Review by GeorgWa — APPROVED** [review]
LGTM

**Comment by jalew188** [comment]
Why sage reader failed? I think we did not change anything.

**Comment by jalew188** [comment]
> Why sage reader failed? I think we did not change anything.

Hmm, this seems to be a random exception on github ...

**Comment by mschwoer** [comment]
unfortunately, it's reproducible, and it does not have to do with the changes in this PR.
Maybe some dependencies changed?
Also, I could still not reproduce it locally.

https://github.com/MannLabs/alphabase/pull/186

**Pull request merged**
