### PR TITLE
Flat lib

### PR DESCRIPTION
**Pull request by jalew188**
Merge fragment_mz_df and fragment_intensity_df into fragment_df in FlatSpecLib by using flatten_fragments(). The new fragment_df looks like:

mz | intensity | type | loss_type | charge | number | position
-- | -- | -- | -- | -- | -- | --
98.060040 | 0.4 | 98 | 0 | 1 | 1 | 0
49.533658 | 0.7 | 98 | 0 | 2 | 1 | 0
769.265157 | 0.6 | 121 | 0 | 1 | 6 | 0
385.136217 | 0.8 | 121 | 0 | 2 | 6 | 0
671.288262 | 0.1 | 121 | 98 | 1 | 6 | 0
... | ... | ... | ... | ... | ... | ...
152.584411 | 0.0 | 121 | 0 | 2 | 2 | 11
1572.620589 | 0.6 | 98 | 0 | 1 | 13 | 12
786.813933 | 0.9 | 98 | 0 | 2 | 13 | 12
175.118952 | 0.3 | 121 | 0 | 1 | 1 | 12
88.063114 | 0.3 | 121 | 0 | 2 | 1

where each column refers to:

* mz:        float, fragment mz value
* intensity: float32, fragment intensity value
* type:      np.int8, ASCII code of the ion type (97=a, 98=b, 99=c, 120=x, 121=y, 122=z), or more ion types in the future. See https://en.wikipedia.org/wiki/ASCII for more ASCII information
* number:    uint32, fragment series number
* position:  uint32, fragment position in sequence (from left to right, starts with 0)
* charge:    int8, fragment charge
* loss_type: int16, fragment loss type, 0=noloss, 17=NH3, 18=H2O, 98=HPO4 (phos), ...

The `frag_start_idx` and `frag_end_idx` in precursor_df will be re-indexed as well.

### CODE REVIEW

**Comment by GeorgWa** [comment]
At the moment the module structure looks like this:
```
spectral_library
   decoy_library
      DecoyLib
   flat_library
      FlatSpecLib
   library_base
      SpecLibBase
```

Furthermore there's
```
protein
   fasta
       FastaLib
```

I think it would be best to align the naming between the different modules and classes and remove redundancy. Personally, If I see the same naming scheme, I assume they are related or belong into the same category. If I see the naming scheme varies I expect there must be a reason.

```
spectral_library
   decoy
      SpecLibDecoy
   flat
      SpecLibFlat
   base
      SpecLibBase
```

We can also go for `BaseLib, FlatLib, DecoyLib` but this would require refactoring the `SpecLibBase` Use across all repositories.

**Comment by GeorgWa** [comment]
Other than this I think we should be good for merging! I will start incorporating the new `FlatSpecLib` class with alphaDIA

**Comment by jalew188** [comment]
> At the moment the module structure looks like this:
> 
> ```
> spectral_library
>    decoy_library
>       DecoyLib
>    flat_library
>       FlatSpecLib
>    library_base
>       SpecLibBase
> ```
> 
> Furthermore there's
> 
> ```
> protein
>    fasta
>        FastaLib
> ```
> 
> I think it would be best to align the naming between the different modules and classes and remove redundancy. Personally, If I see the same naming scheme, I assume they are related or belong into the same category. If I see the naming scheme varies I expect there must be a reason.
> 
> ```
> spectral_library
>    decoy
>       SpecLibDecoy
>    flat
>       SpecLibFlat
>    base
>       SpecLibBase
> ```
> 
> We can also go for `BaseLib, FlatLib, DecoyLib` but this would require refactoring the `SpecLibBase` Use across all repositories.

It makes sense to rename them now, before more repos use it

**Comment by jalew188** [comment]
No, let's do it while we switch to Sphinx, as we are going to add more docs

**Pull request merged**
