### PR TITLE
#215 add FG.ApexIonMobility for SPN report reader

### PR DESCRIPTION
**Pull request by jalew188**

### CODE REVIEW

**Comment by mlorenz49** [comment]
That seems to be correct, I don't have the rights to merge the pull request though.

**Review by mlorenz49 — APPROVED** [review]

**Comment by jalew188** [comment]
@mlorenz49 does it work?

**Comment by mlorenz49** [comment]
Sadly not, the same error as described in the issue appears when running. I attached a screenshot where we can see that the mobility column is being read in at first and is available in self._psm_df. The error is thrown when reaching the function mobility.mobility_to_ccs_for_df in line 509 of the psm_reader.py file.

After running the command `self._psm_df["mobility"][0]` in the debugger the string value `'0.97584784'` is returned.

Changing the value in psm_reader.yaml from `'mobility': ['FG.ApexIonMobility']` to `'mobility': 'FG.ApexIonMobility'` doesnt solve the issue either.

image

**Comment by mlorenz49** [comment]
I found the error:

code on line 176 `df = pd.read_csv(filename, sep=self.csv_sep`) was causing an issue while trying to read in rows with NaN values in the newly added mobiliy column of the spectronaut_reader type. Removing the option `keep_default_na=False` correctly imports the column as float and not as string. NA values are set to 0.0 (not sure how good of a solution that is)

I ran all the tests and they passed. I dont have the rights to push to this branch though.

**Pull request merged**
