### PR TITLE
Add option to specify own config file

### PR DESCRIPTION
**Pull request by ammarcsj**
Minor change so user can provide their own .yaml to specify which files to support

### CODE REVIEW

**Comment by GeorgWa** [comment]
I missed the PR, will take a look tomorrow.

**Comment by ammarcsj** [comment]
Indeed I changed the base to development

**Comment by GeorgWa** [comment]
Looks good to me 👍🏻 
Can you run nbdev_clean once and then we can merge?

Sorry for the delay 🤦🏻 😄

**Comment by ammarcsj** [comment]
thanks for checking, nbs are cleaned

**Pull request merged**
